### ISSUE TITLE
Incorrect cycles?

### ISSUE THREAD

**Issue by davidtranhq** [superzazu/8080#2]
Most likely just a typo. In the cycle table, the cycles for `XCHG` is listed as 5, when it should be 4.

Or, the cycles for "CALL adr" should be 17, while the table only adds 11.

**Comment by superzazu** [comment]
Hello,

Thank you for opening the issue, the cycle count has been fixed for CALL and XCHG in 0a8769514bbabd679326d4139f0a04f7a5bfc578.
